service: data-engineering-jobs

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-2
  logRetentionInDays: 60
  timeout: 900

plugins:
  - serverless-python-requirements

package:
  individually: true

functions:

  elt_zoho_crm:
    handler: jobs.elt_serpstack
    description: Function to retrieve and upload Serpstack API data
    # timeout: 5 # seconds
    # memorySize: 128 # mb
    # package:
    #   patterns:
    #     - "!node_modules/**"
    #     - "!yarn.lock"
    #     - "!package-lock.json"
    #     - "!package.json"